### ISSUE TITLE
Selecting any knife removes the knife. Only default knife can be equipped.

### ISSUE THREAD

**Issue by RaghavTheCyberdude** [kaganus/weapons#26] opened 2017-11-15 14:41 UTC
The !ws menu is working awesome. All skins and Name-tags can be used, but the !knife menu is not working.
Selecting any knife just removes the default knife, (the player is left without any knife). Selecting default knife again and re-spawning brings back the default knife.
I have checked and double checked everything, removed conflicts, reinstalled fresh copy of dedicated server. Still not working.

Please help.

Plugin Version: 1.1.1
SourceMod Version: 1.8.0.6027
pTaH Version: 1.0.8-build10

**Comment by tigocesar** [comment] 2017-11-15 15:15
Same problem here. But with version 1.0.7 linux pTaH 
Plugin Version: 1.1.1
SourceMod Version: 1.8.0.6027
pTaH Version: 1.0.7-build9 linux

**Comment by RaghavTheCyberdude** [comment] 2017-11-17 15:40
@kaganus

**Comment by kaganus** [comment] 2017-11-17 19:37
im not gonna take a look (not that there is anything to look at, only a claim that i cannot reproduce) until more people encounter the problem you say youre having. coz im not having it, neither all my rented servers with this plugin, and no one in my steam friend list.

you probably are doing something wrong, find it yourself

**Comment by b3none** [comment] 2018-02-17 01:46
This used to happen to me when Sourcemod was making sure that the server was following the Valve Server Guidelines as this plugin will result in a token ban. It's Sourcemods version of a defence system for your GSLTs.

You'll need to go to the core.cfg and set the following value:
addons/sourcemod/configs/core.cfg
```
/**
 * Per "http://blog.counter-strike.net/index.php/server_guidelines/", certain plugin
 * functionality will trigger all of the game server owner's Game Server Login Tokens
 * (GSLTs) to get banned when executed on a Counter-Strike: Global Offensive game server.
 *
 * Enabling this option will block plugins from using functionality that is known to cause this.
 * This option only has any effect on CS:GO. Note that this does NOT guarantee that you cannot
 * receive a ban.
 *
 * Disable this option at your own risk.
*/
"FollowCSGOServerGuidelines"	"no"
```

If this issue persists then we know it is a plugin issue.

**Comment by kaganus** [comment] 2018-03-07 12:23
@b3none OP said that the skins are working, which means his core.cfg file is correctly set up. "FollowCSGOServerGuidelines" do not interfere with the way this plugin handles knives. So even if you have it as "yes" in your core.cfg, you will still get different types of knives properly (thanks to PTaH extension). What you won't be able to get is the skins on weapons or knives using !ws. Since that feature is working correctly, i suspect OP was using another plugin that was trying to do something with the player knives that was incompatible. Also what's with the downvote?

As there were no feedbacks from the OP for a very long time, I'm gonna close this now

**Closed by kaganus** 2018-03-07 12:23 UTC

**Comment by b3none** [comment] 2018-03-07 16:46
@kaganus The down vote was because you could have handled the situation better by offering a solution or advice as opposed to telling him to "Find it yourself".
